# yaml-language-server: $schema= https://raw.githubusercontent.com/jesseduffield/lazygit/master/schema/config.json

gui:
  nerdFontsVersion: "3"
  language: "en"
  switchTabsWithPanelJumpKeys: true
  statusPanelView: allBranchesLog
  # border: 'hidden'

  showNumstatInFilesView: true
  showRandomTip: false
  showBottomLine: false
  filterMode: fuzzy
  showCommandLog: false
  sidePanelWidth: 0.25
  expandFocusedSidePanel: true
  expandedSidePanelWeight: 4
  branchColorPatterns:
    '^[Bb]ugfix': 'red'
    '^[Ff]eature': 'green'
    '^[Pp]roject': 'blue'
    '^develop': 'magenta'
    '^[Rr]elease': 'cyan'
    '^(master|main)': 'yellow'
  spinner:
    rate: 83
    frames: ['', '', '', '', '', '']
  theme:
    activeBorderColor:
      - "#aeaed1"
      - "bold"
    inactiveBorderColor:
      - "#606079"
    optionsTextColor:
      - "#606079"
    selectedLineBgColor:
      - "#252530"
    cherryPickedCommitFgColor:
      - "#d8647e"
    cherryPickedCommitBgColor:
      - "bg"
    markedBaseCommitFgColor:
      - "#f3be7c"
    markedBaseCommitBgColor:
      - "bg"
    unstagedChangesColor:
      - "#d8647e"
    defaultFgColor:
      - "#cdcdcd"
  # theme:
  #   activeBorderColor:
  #     - blue
  #     - bold
  #   inactiveBorderColor:
  #     - black
  #     - bold
  #   selectedLineBgColor:
  #     - reverse
  customIcons:
    extensions:
      ".http":
        icon: "\U000F109B"
        color: '#5050FF'
git:
  localBranchSortOrder: recency
  mainBranches: [main, master, develop]
  pagers:
    - externalDiffCommand: "$HOME/.config/lazygit/scripts/pager.ps1"
      useExternalDiffGitConfig: true
    - pager: 'delta --dark --paging=never'
      useExternalDiffGitConfig: true
      colorArg: always
notARepository: 'quit'
os:
  open: 'nvim {{filename}}'
  editPreset: 'nvim'
